[package]
name = "hydrogen-i18n"
version = "2.0.0"
authors = ["Nashira Deer <nashiradeer@gmail.com>"]
edition = "2021"
description = "In-memory translation manager designed for use by Discord apps and bots that work with multiple users with different languages at the same time."
repository = "https://github.com/nashiradeer/hydrogen"
readme = "README.md"
license = "MIT"
keywords = ["hydrogen", "i18n", "language", "l10n", "translation"]
categories = ["internationalization", "localization"]

[features]
default = []
serenity = ["dep:serenity"]

[dependencies]
serde_json = "1.0.99"

[dependencies.serenity]
package = "serenity"
version = "0.12.0"
optional = true
default-features = false
features = ["builder"]
