[package]
name = "hydrogen-i18n"
version = "2.0.0"
authors = ["Nashira Deer <nashiradeer@gmail.com>"]
edition = "2021"
description = "Translation utilities for server-side applications that need to deals with different languages on the same time."
repository = "https://github.com/nashiradeer/hydrogen-i18n"
readme = "README.md"
license = "MIT"
keywords = ["hydrogen", "i18n", "language", "l10n", "translation"]
categories = ["internationalization", "localization"]

[features]
default = []
serenity = ["dep:serenity"]
tokio = ["dep:tokio"]
simd = ["dep:simd-json"]

[dependencies]
serde_json = "1.0.99"

[dependencies.serenity]
package = "serenity"
version = "0.12.0"
optional = true
default-features = false
features = ["builder"]

[dependencies.tokio]
package = "tokio"
version = "1.35.1"
optional = true
default-features = false
features = ["fs"]

[dependencies.simd-json]
package = "simd-json"
version = "0.13.7"
optional = true
features = ["serde_impl"]
