name: Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: "1.75"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust ${{ env.RUST_VERSION }}
        run: rustup install ${{ env.RUST_VERSION }}
      - name: Set Rust  ${{ env.RUST_VERSION }} as default
        run: rustup default ${{ env.RUST_VERSION }}
      - name: Check
        run: cargo check --config 'build.rustflags = ["-Dwarnings"]' --all-features
      - name: Install Clippy
        run: rustup component add clippy
      - name: Run Clippy
        run: cargo clippy --config 'build.rustflags = ["-Dwarnings"]' --all-features
