name: Main workflow

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: "1.80"

jobs:
  check:
    name: Check syntax
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust ${{ env.RUST_VERSION }}
        run: rustup install ${{ env.RUST_VERSION }}
      - name: Set Rust  ${{ env.RUST_VERSION }} as default
        run: rustup default ${{ env.RUST_VERSION }}
      - name: Install clippy
        run: rustup component add clippy
      - name: Run check
        run: cargo check --config 'build.rustflags = ["-Dwarnings"]' --features "test-util"
      - name: Run clippy
        run: cargo clippy --config 'build.rustflags = ["-Dwarnings"]' --features "test-util"
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust ${{ env.RUST_VERSION }}
        run: rustup install ${{ env.RUST_VERSION }}
      - name: Set Rust  ${{ env.RUST_VERSION }} as default
        run: rustup default ${{ env.RUST_VERSION }}
      - name: Run tests
        run: cargo test --features "test-util"
