name: Test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always
  RUST_VERSION: "1.75"

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Rust ${{ env.RUST_VERSION }}
        run: rustup install ${{ env.RUST_VERSION }}
      - name: Set Rust  ${{ env.RUST_VERSION }} as default
        run: rustup default ${{ env.RUST_VERSION }}
      - name: Test with default features
        run: cargo test
      - name: Test with all features
        run: cargo test --all-features
